FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=120 \
    -r requirements.txt

COPY app ./app

CMD ["python", "-m", "app.telegram.bot"]
